### ISSUE TITLE
Indice dei contenuti

### ISSUE THREAD

**Issue by bertof** [jack793/SWE-Glossary#1]
Sarebbe utile un indice delle sezioni (autogenerato) nelle pagine iniziali con a ciascuna lettera iniziale dei termini la pagina a cui tali termini iniziano. Una lista del tipo:
A - pag 2
B - pag 4
Ecc

**Comment by jack793** [comment]
Eh si non è cattiva idea..non so come ma vedrò xD

**Comment by bertof** [comment]
Poi provo anche io a metterci le mani.

**Comment by jack793** [comment]
Okay

**Comment by bertof** [comment]
Sono riuscito a far generare correttamente il file degli indici, ma non riesco a farlo visualizzare nella table of contents. Rimane soltanto l'indice generale del glossario. Qualche idea?

**Comment by jack793** [comment]
Avevo già provato ma per inserire tutte le entry ma non riuscivo=( che intendi per file degli indici?

**Comment by jack793** [comment]
Hai zenhub cmq installato? :)

**Comment by bertof** [comment]
Questo file, che contiene il markup autogenerato degl'indici del glossario
[Glossario.zip](https://github.com/jack793/SWE-Glossary/files/546385/Glossario.zip)

**Comment by bertof** [comment]
Ora provo zenhub (ne ero andato in cerca, ma non mi ricordavo il nome)

**Comment by jack793** [comment]
Ah il makeindex ok si bella =)
